#program to demonstrate the use of finally block in exception handling. 
try:
    print("hello i am practicing exception handling")
except:
    print("something went wrong")
else:
    print("nothing went wrong")
finally:
    print("this will always run")